#!/usr/bin/env bash
# -t | --truncate || Whether to (truncate) or keep the trailing delimiter at the end of each value. (Boolean flag)
# -d | --delimiter || Tells the function which character delimitates the values; falls back to newline if none provided. (Argument required)
# Post-option Positional Argument 1 || Which variable name to map the values to.
#
arrayify() {
	local exit args truncate IFS=$'\n'
	args="$(getopt --options 'td:' --longoptions 'truncate,delimiter:' --name "$0" -- "$@")" || return 252
	eval set -- "${args}"
	while true; do
		case "$1" in
			-t|--truncate)
				truncate=true
				shift
			;;
			-d|--delimiter)
				IFS="$2"
				shift 2
				if [[ "${#IFS}" -gt 1 ]]; then
					log e 'The IFS must be 1 singular character or a nullbyte.'
					exit=253
				fi
			;;
			--)
				shift
				break
			;;
			*)
				break
			;;
		esac
	done
	#
	# Makes "arrayify_internal_array" a "symlink" to the given array.
	# Variable name needs to be long to avoid collision with other variables.
	declare -n internal_array="$1"
	#
	# Do the appending.
	# The wonderful "while read ...;" loop is great,
	# but drops the last line of a file if there is no trailing delim.
	# Because the -d (delimiter) condition is no longer true.
	for path in "${@:2}"; do
		if [[ ! -f "${path}" ]]; then
			log e "\"${path}\" is not a valid filepath."
			exit=255
		fi
		[[ -n "${exit}" ]] && return "${exit}"
		while read -rd "${IFS}" line || [[ -n "${line}" ]]; do
			if [[ -n "${truncate}" && -n "${IFS}" ]]; then internal_array+=("${line}")
			else internal_array+=("${line}${IFS}")
			fi
		done </dev/stdin
	done
}
#
# Replace builtins.
enable -n mapfile readarray
mapfile() { arrayify "$@"; }
readarray() { arrayify "$@"; }
declare -rfx arrayify mapfile readarray