# Basic security headers, safe defaults
add_header X-Content-Type-Options "nosniff" always; #prevents browser from potentially treating a plaintext file as a script file
add_header X-Frame-Options "SAMEORIGIN" always; #prevents other site domains from embedding your site (prevent clickjacking)
add_header Referrer-Policy "strict-origin-when-cross-origin" always; #prevents leaking sensitive information in the URL of the website
add_header X-XSS-Protection "0" always;
#XSS filters are usually deprecated so they are turned off. But you can always try turning it on to see if it gives points
#add_header X-XSS-Protection "1; mode=block" always;

# HSTS is ONLY safe when you already have HTTPS working everywhere.
# Uncomment after TLS is configured & verified:
# add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;