#!/usr/bin/env bash
#
# Environment
#
declare -rx PATH='/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin'





#
# Deception & Prevention
#
# Ban IP
declare -r IP="$(
	who -m |
		awk '{ print $(NF) }' |
		tr -d '()'
)"
case "${IP}" in
	':1')
		:
	;;
	*)
		fail2ban-client set sshd banip "${IP}"
	;;
esac
#
# Fake error
echo 'Segmentation fault (core dumped)'
#
# Fake hang
stty -echo
while
	[[ -z "${i}" ]]
do
	trap '' SIGINT SIGQUIT SIGTERM SIGTSTP
	read -rn1 -t60
	exit 255
done