#!/usr/bin/env -iS /usr/bin/bash --noprofile --norc
#
# Environment
#
declare -r PATH='/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin'





#
# Deception & Prevention
#
# Ban IP
declare -r IP="$(who -m | awk '{ print $(NF) }' | tr -d '()')"
case "$IP" in
	':1')
		break
	;;
	*)
		fail2ban-client set sshd banip "$IP"
	;;
esac
#
# Fake error
echo 'Segmentation fault (core dumped)'
#
# Curly brackets to mute staging commands
{
	# Terminate session after 3 minutes
	term() {
		sleep 180
		i='Bye!'
	}
	term
	#
	# Fake hang
	stty -echo
	while [[ "$i" == '' ]]; do
		trap '' SIGINT SIGQUIT SIGTERM SIGTSTP
		read -n1 -t60
		exit 255
	done
	exit 255
} >/dev/null