#!/usr/bin/env bash
# Grab args
title="$1"
type="$2"
shift 2
opts=("$@")
#
# Display options
clear >&2
[[ -z "${preprompt_msg}" ]] && echo -- "${preprompt_msg}" >&2
echo "${title}" >&2
for item in "${@}"; do
	x="$((x + 1))"
	item="${x}) ${item}"
	printf '\t%s\n' "${item}" >&2
done
#
# Determinte selection mode & grab selection(s)
if [[ "${type}" == checklist ]]; then
	cat >&2 <<-'EOF'
		Enter your selections—separated by spaces.
		(i.e. "1 4 6 9")
	EOF
elif [[ "${type}" == radiolist ]]; then
	cat >&2 <<-'EOF'
		Enter a single selection
		(i.e. "5")
	EOF
else
	cat >&2 <<-EOF
		Incorrect usage of the checklist function;
		"${type}" was given as the 2nd argument, but the only valid options are "checklist" OR "radiolist".
	EOF
	exit 1
fi
read -erp 'Type your selection(s) then press [ENTER] to submit: ' -a selections >&2
#
# Do nothing with empty responses
# Validate user choices & return the choices
[[ -z "${selections[*]}" ]] && exit 0
for selection in "${selections[@]}"; do
	[[
		"${selection}" =~ ${num_chk} &&
		"${selection}" -gt 0 &&
		"${selection}" -le "${#opts[@]}"
	]] && echo "${opts["$(("${selection}" - 1 ))"]}"
done