#!/usr/bin/env bash
#
# URL Simplification
#
# URL to compare against.
official_url="${1#*://}"
official_url="${official_url%%/*}"
official_url="${official_url%:*}"
official_url="${official_url#www.}"
#
# URL given to compare.
repo_url="${2#*://}"
repo_url="${repo_url%%/*}"
repo_url="${repo_url%:*}"
repo_url="${repo_url#www.}"





#
# Comparison
#
# If URL to compare exists and matches right-to-left, return success.
[[ -n "${repo_url}" && "${repo_url}" =~ ^(.+\."${official_url}"|"${official_url}")$ ]]