#!/usr/bin/env bash
type="$1"
shift 1
case "${type}" in
	i) printf "\x1b[48;5;18mℹ: %s" "$*";;
	w) printf "\x1b[48;5;58mW: %s" "$*" >&2;;
	e) printf "\x1b[48;5;88mE: %s" "$*" >&2;;
	*) exit 255;;
esac
printf '\x1b[0m\n'