#!/usr/bin/env bash
# shellcheck disable=SC2154
# The divider used to delimitate the key and value; and the target file.
# Defined via an environment variable to avoid extreme repetition.
# Remove any existing keys & then add the new entry
touch "${target_file}"
grep -qE "^[^#].*$1${delimiter}.*$" "${target_file}" &&
	sed -i "s/^[^#]*$1.*$/$1${delimiter}$2/" "${target_file}" ||
	echo -- "$1${delimiter}$2" >>"${target_file}"