#!/usr/bin/env bash
# IMPROVE LATER
key="$(echo "$1" | cut -d' ' -f1)"
value="$(echo "$1" | cut -d' ' -f2)"
file="$2"
divider="${divider: }"
#
# Remove any existing keys & then add the new entry
sed -i "/^[\s#]*${key}/d" "${file}"
echo -- "${key}${divider}${value}" >>"${file}"