[Service]
ProtectProc=invisible
SystemCallArchitectures=native
RestrictAddressFamilies=AF_INET AF_INET6
NoNewPrivileges=true
MemoryDenyWriteExecute=true
LockPersonality=true
UMask=0077
PrivateTmp=true
PrivateDevices=true
NoExecPaths=/tmp /var/tmp /dev/shm
ProtectHome=tmpfs
ProtectSystem=full
ProtectHostname=true
SystemCallFilter=@system-service @network-io @basic-io
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectKernelTunables=true
ProtectControlGroups=true
ProtectClock=true
RestrictNamespaces=true
CapabilityoundingSet=CAP_NET_BIND_SERVICE
ReadWritePaths=/var/log/apache2/ /var/run/apache2/ /run/apache2/
RestrictSUIDSGID=true
RemoveIPC=true
