[Service]
ProtectProc=invisible
SystemCallArchitectures=native
RestrictAddressFamilies=AF_INET AF_INET6
NoNewPrivileges=yes
MemoryDenyWriteExecute=yes
LockPersonality=yes
UMask=0077
PrivateTmp=yes
PrivateDevices=yes
NoExecPaths=/tmp /var/tmp /dev/shm
ProtectHome=yes
ProtectSystem=full
ProtectHostname=yes
SystemCallFilter=@system-service @network-io @basic-io
ProtectKernelModules=yes
ProtectKernelLogs=true
ProtectKernelTunables=yes
ProtectControlGroups=yes
ProtectClock=yes
RestrictNamespaces=yes
CapabilityoundingSet=CAP_NET_BIND_SERVICE
ReadWritePaths=/var/log/apache2/ /var/run/apache2/ /run/apache2/
RestrictSUIDSGID=yes
RemoveIPC=yes
