[Service]
# Restrict file system access
ProtectSystem=full
ProtectHome=yes
PrivateTmp=yes

# Restrict device and kernel access
PrivateDevices=yes
ProtectControlGroups=yes
ProtectKernelTunables=yes

# Disable unnecessary privileges
NoNewPrivileges=yes

SystemCallFilter=~@clock ~@cpu-emulation ~@debug ~@module ~@mount ~@obsolete ~@swap ~@privileged ~@resources