[Service]
# Modify for your use case.
ProtectSystem=strict
ProtectHome=tmpfs

# Basically never needs these
ProtectProc=invisible
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectKernelTunables=true
ProtectControlGroups=true
ProtectClock=true
ProtectHostname=true
ProtectControlGroups=true
ProtectKernelTunables=true
RemoveIPC=true

# Usually doesn't need to look into devices, users or the global /tmp.
PrivateTmp=true
PrivateUsers=true
PrivateDevices=true

# Remove priv-esc
NoNewPrivileges=true

# Probably doesn't need to do anything else but these things
SystemCallArchitectures=native
SystemCallFilter=@system-service @network-io @basic-io