[Service]
MemoryDenyWriteExecute=true
UMask=0077
RuntimeDirectoryMode=755
ProtectHome=strict
PrivateTmp=true
NoNewPrivileges=true
CapabilityBoundingSet=
AmbientCapabilities=
LockPersonality=true
RestrictNamespaces=true
ProtectSystem=strict
ReadWritePaths=/var/lib/mysql /var/log/mysql /run/mysqld
MemoryMax=1G
TasksMax=596
RestrictSUIDSGID=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectKernelTunables=true
ProtectControlGroups=true
ProtectClock=true
ProtectHostname=true
ProtectProc=invisible
SystemCallArchitectures=native
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
NoNewPrivileges=true
PrivateDevices=true
PrivateUsers=true
SystemCallFilter=~@clock ~@cpu-emulation ~@debug ~@module ~@mount ~@obsolete ~@swap ~@privileged ~@resources