[Service]
ExecStartPre=

User=mosquitto
Group=mosquitto

NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=full
ProtectHome=strict
PrivateUsers=yes
PrivateDevices=yes
ProtectClock=yes
UMask=0077
ProtectProc=invisible
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
CapabilityBoundingSet=~CAP_NET_ADMIN ~CAP_SYS_ADMIN CAP_SYS_PTRACE CAP_KILL CAP_NET_RAW
SystemCallFilter=~@clock ~@cpu-emulation ~@debug ~@module ~@mount ~@obsolete ~@raw-io ~@reboot ~@swap ~@privileged ~@resources
MemoryDenyWriteExecute=yes
RemoveIPC=yes
StateDirectory=mosquitto