[Service]
# User=postgres
# Group=postgres
# RuntimeDirectory=postgresql
UMask=0077
RuntimeDirectoryMode=0755
ProtectHome=strict
PrivateTmp=true
NoNewPrivileges=true
CapabilityBoundingSet=
AmbientCapabilities=
LockPersonality=true
RestrictNamespaces=yes
ProtectSystem=strict
ReadWritePaths=/home
RefuseManualStop=yes
MemoryMax=1G
TasksMax=596
RestrictSUIDSGID=yes
ProtectKernelModules=yes
ProtectKernelLogs=true
ProtectKernelTunables=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
ProtectProc=invisible
SystemCallArchitectures=native
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
NoNewPrivileges=yes
PrivateDevices=yes
PrivateUsers=true
SystemCallFilter=~@clock ~@cpu-emulation ~@debug ~@module ~@mount ~@obsolete ~@swap ~@privileged ~@resources