[Service]
# Restrict control access (crucial for a service with high privilege)
ProtectControlGroups=yes
ProtectKernelTunables=yes
LockPersonality=yes

# Restrict memory/capabilities
MemoryDenyWriteExecute=yes
NoNewPrivileges=yes