# Require length of 10 + 1 all 4 character types
minlen = 10
dcredit = -1
ucredit = -1
lcredit = -1
ocredit = -1
#
# Similarity / repetition limits
difok = 4
maxrepeat = 4
maxclassrepeat = 4
retry = 3
enforce_for_root